### ISSUE TITLE
En tant qu’utilisateur de l’application, je veux avoir accès à des indications spécifiques à un tableau

### ISSUE THREAD

**Issue by Jubegue** [ArmandLeclerc/Kadre#1]

**Comment by ArmandLeclerc** [comment]
- reconnaissance visuelle des tableaux
- avoir une page spécifique par tableau
- sur cette page, afficher les champs d’informations (artiste, date, courant, anecdote)
- renvoyer la page du tableau reconnu

**Comment by ArmandLeclerc** [comment]
Première version des issues incorrecte, ne pas prendre en compte.
