### ISSUE TITLE
En tant que membre communication d’un musée, je veux que les informations sur les expositions à venir soient transmises aux personnes consultant les informations de  tableaux présents dans mon musée.

### ISSUE THREAD

**Issue by Jubegue** [ArmandLeclerc/Kadre#2]

**Comment by ArmandLeclerc** [comment]
- détecter la géolocalisation
- afficher des informations géolocalisées
- donner la possibilité depuis un compte contributeur de mettre en place des informations géolocalisées (contre paiement ? Gratuit pour partenaires ?)

**Comment by ArmandLeclerc** [comment]
Première version des issues incorrecte, ne pas prendre en compte.
