### ISSUE TITLE
En tant que connaisseur/expert d’art, je veux rajouter des informations afin de compléter la fiche d’une oeuvre

### ISSUE THREAD

**Issue by Jubegue** [ArmandLeclerc/Kadre#3]

**Comment by ArmandLeclerc** [comment]
- créer un profil contributeur
- permettre d’accéder à la fiche d’une oeuvre et proposer révision
- mettre en place un système de vérification par les pairs

**Comment by ArmandLeclerc** [comment]
Première version des issues incorrecte, ne pas prendre en compte.
