### ISSUE TITLE
En tant qu’utilisateur, je veux pouvoir trouver des oeuvres par thématique

### ISSUE THREAD

**Issue by Jubegue** [ArmandLeclerc/Kadre#4]

**Comment by ArmandLeclerc** [comment]
- créer une base de données regroupant les œuvres par thématique
- créer un champ de recherche par thématique côté utilisateur
- affichage de la location des différentes œuvres (quelles œuvres sont ici ? ou en trouver d’autres ?)

**Comment by ArmandLeclerc** [comment]
Première version des issues incorrecte, ne pas prendre en compte.
